/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;

/**
 *
 * @author admin
 */
public class empUI extends javax.swing.JFrame {
    public String empname ;
    boolean taskcheck= true;
    /**
     * Creates new form empUI
     */
    public empUI() {
       initComponents();
       
    }
    
    public empUI(String userID) {
       empname = userID;
       initComponents();
       name.setText(empname);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        welcome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        edit = new javax.swing.JButton();
        timesheet = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        change = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        oldpass = new javax.swing.JPasswordField();
        newpass = new javax.swing.JPasswordField();
        repass = new javax.swing.JPasswordField();
        confirm = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(77, 5, 232));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Page");

        jPanel1.setBackground(new java.awt.Color(77, 5, 232));

        welcome.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        welcome.setText("Welcome");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/icon/time-manager.png"))); // NOI18N

        name.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        name.setText("Name#");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(41, 241, 195));
        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        jPanel4.setBackground(new java.awt.Color(41, 241, 195));
        jPanel4.setLayout(null);

        edit.setBackground(new java.awt.Color(77, 5, 232));
        edit.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setText("Edit Profile");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel4.add(edit);
        edit.setBounds(0, 161, 220, 40);

        timesheet.setBackground(new java.awt.Color(41, 241, 195));
        timesheet.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        timesheet.setForeground(new java.awt.Color(255, 255, 255));
        timesheet.setText("Time sheets");
        timesheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timesheetActionPerformed(evt);
            }
        });
        jPanel4.add(timesheet);
        timesheet.setBounds(225, 161, 220, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/icon/resume.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel1);
        jLabel1.setBounds(0, 0, 220, 160);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/icon/time.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel3);
        jLabel3.setBounds(230, 0, 220, 160);

        jPanel2.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(41, 241, 195));
        jPanel5.setForeground(new java.awt.Color(77, 5, 232));
        jPanel5.setEnabled(false);

        change.setBackground(new java.awt.Color(255, 153, 0));
        change.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        change.setForeground(new java.awt.Color(255, 255, 255));
        change.setText("Change your password");
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(255, 0, 0));
        back.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Quit");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/icon/Userpassword.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(77, 5, 232));
        jLabel5.setText("Old Password");

        jLabel6.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(77, 5, 232));
        jLabel6.setText("New Password");

        jLabel7.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(77, 5, 232));
        jLabel7.setText("Re-enter");

        oldpass.setEnabled(false);
        oldpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                oldpassKeyPressed(evt);
            }
        });

        newpass.setEnabled(false);
        newpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                newpassKeyPressed(evt);
            }
        });

        repass.setEnabled(false);
        repass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                repassKeyPressed(evt);
            }
        });

        confirm.setBackground(new java.awt.Color(0, 255, 0));
        confirm.setText("Confirm");
        confirm.setEnabled(false);
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });

        cancel.setBackground(new java.awt.Color(0, 0, 255));
        cancel.setText("Cancel");
        cancel.setEnabled(false);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(change, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(repass, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(newpass)
                                    .addComponent(oldpass)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(confirm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(oldpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(newpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(repass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(change, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        if(taskcheck==true){
        this.setVisible(false);
        new EmpApp(empname).setVisible(true);
        }else{
        JOptionPane.showMessageDialog(null, "Finish other tasks first");
        }
    }//GEN-LAST:event_editActionPerformed

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
        // TODO add your handling code here:
        cancel.setEnabled(true);
        confirm.setEnabled(true);
        change.setEnabled(false);
        oldpass.setEnabled(true);
        newpass.setEnabled(true);
        repass.setEnabled(true);
         taskcheck = false;
    }//GEN-LAST:event_changeActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        cancel.setEnabled(false);
        confirm.setEnabled(false);
        change.setEnabled(true);
        oldpass.setEnabled(false);
        newpass.setEnabled(false);
        repass.setEnabled(false);
        oldpass.setText("");
        newpass.setText("");
        repass.setText("");
        taskcheck = true;
    }//GEN-LAST:event_cancelActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null,null, "Are you sure !!",YES_NO_OPTION,JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.YES_OPTION){
                this.setVisible(false);
                new Login().setVisible(true); 
        }
    }//GEN-LAST:event_backActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
           ResultSet rs;
        String repass1 = "[A-Za-z0-9]{3,7}$"; 
        if(oldpass.getText().equals("")||newpass.getText().equals("")||repass.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Fields cannot be blank !!!");
            return;
        }
        int result = JOptionPane.showConfirmDialog(null,"Confirm this form ?", "Submit ?",YES_NO_OPTION,JOptionPane.PLAIN_MESSAGE);
            if (result == JOptionPane.YES_OPTION){
             
                    try{
                     Class.forName("org.hsqldb.jdbc.JDBCDriver");
                     try (
                     Connection con = DriverManager.getConnection("jdbc:hsqldb:file:HSQL/managing", "root", "")) {
                    //here manager is database name, root is username and password
                    Statement stmt = (Statement) con.createStatement();
                    String query = "SELECT password FROM emp WHERE name = '"+empname+"'";
                    rs =stmt.executeQuery(query);
                    //stmt.executeUpdate(query);
                   // JOptionPane.showMessageDialog(null, "Saved to Database !!!");
                   rs.next();
                   String checkpass = (rs.getString(1));
                   if(!oldpass.getText().matches(checkpass)){
                       JOptionPane.showMessageDialog(null, "Your inserted password not match your current password!!!");
                   }
                   else{
                        if(!newpass.getText().matches(repass1)){
                             JOptionPane.showMessageDialog(null, "Password must contains 3-7 character and can not use space or special character  !!!");
                            
                             }
                        else if(!newpass.getText().matches(repass.getText())){
                         JOptionPane.showMessageDialog(null, "Password not match!!!");
                        }
                        else if(newpass.getText().matches(oldpass.getText())){
                         JOptionPane.showMessageDialog(null, "New Password can't be the same with the old one!!!");
                        }
                        else{
                            String query1 = " UPDATE emp "
                                    + "SET password='"+newpass.getText()+"' WHERE  name = '"+empname+"'";
                            stmt.executeUpdate(query1);
                            JOptionPane.showMessageDialog(null, "Password was changed !!!");
                           oldpass.setEnabled(false);
                           newpass.setEnabled(false);
                           repass.setEnabled(false);
                           oldpass.setText("");
                           newpass.setText("");
                           repass.setText("");
                           confirm.setEnabled(false);
                           cancel.setEnabled(false);
                           change.setEnabled(true);
                           taskcheck = true;
                        }
                   }
                }       catch (SQLException ex) {
                            ex.printStackTrace();
                        }
            }catch(ClassNotFoundException e){JOptionPane.showMessageDialog(null, "Class not found !!!");}
               }
        
    }//GEN-LAST:event_confirmActionPerformed

    private void timesheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timesheetActionPerformed
        // TODO add your handling code here:
        if(taskcheck==true){
          this.setVisible(false);
        new TimeSheets(empname).setVisible(true);
        }else{
        JOptionPane.showMessageDialog(null, "Finish other tasks first");
        }
    }//GEN-LAST:event_timesheetActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        change.doClick();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        timesheet.doClick();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        edit.doClick();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void repassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_repassKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        confirm.doClick();
       }
        
    }//GEN-LAST:event_repassKeyPressed

    private void newpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newpassKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        confirm.doClick();
       }
    }//GEN-LAST:event_newpassKeyPressed

    private void oldpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oldpassKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        confirm.doClick();
       }
    }//GEN-LAST:event_oldpassKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(empUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(empUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(empUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(empUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new empUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton cancel;
    private javax.swing.JButton change;
    private javax.swing.JButton confirm;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel name;
    private javax.swing.JPasswordField newpass;
    private javax.swing.JPasswordField oldpass;
    private javax.swing.JPasswordField repass;
    private javax.swing.JButton timesheet;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
