/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;

/**
 *
 * @author admin
 */
public final class TimeSheets extends javax.swing.JFrame {
    String empname;   
    String userID;
    String renum="[0-9]{1,100}";
    /**
     * Creates new form TimeSheets
     */
    public TimeSheets() {
        initComponents();
    }
    
     public TimeSheets(String userID) {
         empname = userID;
        initComponents();
        name.setText(empname);
        onLoad();
        
    }
       public void onLoad(){
         
        try{
            Class.forName("org.hsqldb.jdbc.JDBCDriver");
            try (Connection con = DriverManager.getConnection(
               "jdbc:hsqldb:file:HSQL/managing", "root", "")) {
            //here manager is database name, root is username and password
            Statement stmt=(Statement) con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs=stmt.executeQuery("select id from emp where name ='"+empname+"'");
            //show it on screen
            rs.first();
            userID=rs.getString(1);
             ResultSet rs1=stmt.executeQuery("select * from monthly where id ='"+userID+"'");
            rs1.first();
            h1.setText(rs1.getFloat(2)+" hours");
            h2.setText(rs1.getFloat(3)+" hours");
            h3.setText(rs1.getFloat(4)+" hours");
            h4.setText(rs1.getFloat(5)+" hours");
            h5.setText(rs1.getFloat(6)+" hours");
            h6.setText(rs1.getFloat(7)+" hours");
            h7.setText(rs1.getFloat(8)+" hours");
            h8.setText(rs1.getFloat(9)+" hours");
            h9.setText(rs1.getFloat(10)+" hours");
            h10.setText(rs1.getFloat(11)+" hours");
            h11.setText(rs1.getFloat(12)+" hours");
            h12.setText(rs1.getFloat(13)+" hours");
         }
        }catch(ClassNotFoundException | SQLException e){ JOptionPane.showMessageDialog(null, "Cannot connect Database !!!");}
          
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        January = new javax.swing.JButton();
        h1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        February = new javax.swing.JButton();
        h2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        March = new javax.swing.JButton();
        h3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        April = new javax.swing.JButton();
        h4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        May = new javax.swing.JButton();
        h5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        June = new javax.swing.JButton();
        h6 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        July = new javax.swing.JButton();
        h7 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        August = new javax.swing.JButton();
        h8 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        September = new javax.swing.JButton();
        h9 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        October = new javax.swing.JButton();
        h10 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        November = new javax.swing.JButton();
        h11 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        December = new javax.swing.JButton();
        h12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel13.setFont(new java.awt.Font("HG創英ﾌﾟﾚｾﾞﾝｽEB", 1, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("2020専門学校日本国際ITカレッジ　18069　ファム　アイン　コン");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Time Sheets");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(77, 5, 232));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/icon/time-manager.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        name.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        name.setText("Name#");

        jLabel3.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel3.setText("Time Sheets");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(41, 241, 195));

        jPanel3.setLayout(new java.awt.GridLayout(2, 6));

        January.setBackground(new java.awt.Color(51, 255, 51));
        January.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        January.setText("January");
        January.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JanuaryActionPerformed(evt);
            }
        });

        h1.setBackground(new java.awt.Color(51, 255, 0));
        h1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        h1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        h1.setText("jLabel4");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(January, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(h1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(January, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(h1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        February.setBackground(new java.awt.Color(51, 255, 51));
        February.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        February.setText("February");
        February.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FebruaryActionPerformed(evt);
            }
        });

        h2.setBackground(new java.awt.Color(51, 255, 0));
        h2.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        h2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        h2.setText("jLabel5");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(February, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(h2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(February, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(h2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        March.setBackground(new java.awt.Color(51, 255, 153));
        March.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        March.setText("March");
        March.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarchActionPerformed(evt);
            }
        });

        h3.setBackground(new java.awt.Color(51, 255, 0));
        h3.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        h3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        h3.setText("jLabel6");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(March, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(h3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(March, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(h3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        April.setBackground(new java.awt.Color(255, 153, 51));
        April.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        April.setText("April");
        April.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AprilActionPerformed(evt);
            }
        });

        h4.setBackground(new java.awt.Color(255, 51, 51));
        h4.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        h4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        h4.setText("jLabel7");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(April, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(h4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(April, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(h4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        May.setBackground(new java.awt.Color(255, 51, 51));
        May.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        May.setText("May");
        May.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MayActionPerformed(evt);
            }
        });

        h5.setBackground(new java.awt.Color(255, 51, 51));
        h5.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        h5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        h5.setText("jLabel8");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(May, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(h5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(May, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(h5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        June.setBackground(new java.awt.Color(255, 51, 102));
        June.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        June.setText("June");
        June.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JuneActionPerformed(evt);
            }
        });

        h6.setBackground(new java.awt.Color(255, 51, 51));
        h6.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        h6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        h6.setText("jLabel9");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(June, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(h6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(June, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(h6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        July.setBackground(new java.awt.Color(255, 255, 153));
        July.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        July.setText("July");
        July.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JulyActionPerformed(evt);
            }
        });

        h7.setBackground(new java.awt.Color(255, 255, 0));
        h7.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        h7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        h7.setText("jLabel15");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(July, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(h7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(July, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(h7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        August.setBackground(new java.awt.Color(255, 255, 102));
        August.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        August.setText("August");
        August.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AugustActionPerformed(evt);
            }
        });

        h8.setBackground(new java.awt.Color(255, 255, 0));
        h8.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        h8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        h8.setText("jLabel14");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(August, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(h8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(August, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(h8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        September.setBackground(new java.awt.Color(255, 255, 0));
        September.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        September.setText("September");
        September.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeptemberActionPerformed(evt);
            }
        });

        h9.setBackground(new java.awt.Color(255, 255, 0));
        h9.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        h9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        h9.setText("jLabel13");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(September, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(h9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(September, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(h9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        October.setBackground(new java.awt.Color(0, 153, 255));
        October.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        October.setText("October");
        October.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OctoberActionPerformed(evt);
            }
        });

        h10.setBackground(new java.awt.Color(0, 0, 204));
        h10.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        h10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        h10.setText("jLabel12");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(October, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(h10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(October, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(h10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        November.setBackground(new java.awt.Color(0, 0, 204));
        November.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        November.setText("November");
        November.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovemberActionPerformed(evt);
            }
        });

        h11.setBackground(new java.awt.Color(0, 0, 204));
        h11.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        h11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        h11.setText("jLabel11");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(November, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(h11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(November, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(h11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        December.setBackground(new java.awt.Color(102, 0, 255));
        December.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        December.setText("December");
        December.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecemberActionPerformed(evt);
            }
        });

        h12.setBackground(new java.awt.Color(0, 0, 204));
        h12.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        h12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        h12.setText("jLabel10");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(December, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(h12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(December, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(h12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel16.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 204, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Edit you work hours by months");

        Back.setBackground(new java.awt.Color(255, 153, 0));
        Back.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("2020JIIT All rights reserved 18069 PHAM ANH CONG ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(266, 266, 266)
                                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(jLabel17)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FebruaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FebruaryActionPerformed
        // TODO add your handling code here:
      
        JFrame Paneframe = new JFrame("InputDialog Example #1");
        String response = JOptionPane.showInputDialog(Paneframe,"Insert your working hours in February here" );
          try{
            Class.forName("org.hsqldb.jdbc.JDBCDriver");
            try (Connection con = DriverManager.getConnection(
               "jdbc:hsqldb:file:HSQL/managing", "root", "")) {
                if(!renum.matches(response)&&Float.valueOf(response)%0.25!=0){
                    JOptionPane.showMessageDialog(null, "Must be number and multiples of 0.25 !");
                }
                else{
                    String query="UPDATE monthly SET \"2\" = '"+ Float.valueOf(response) +"' WHERE id='"+userID+"'";
                    Statement stmt = (Statement) con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                    stmt.executeUpdate(query);
                    String hwage = "SELECT hswage FROM emp WHERE id = '"+ userID +"'";
                    ResultSet rs = stmt.executeQuery(hwage);
                     rs.first();
                    if(rs.getString(1).matches("0.0")){
                          float salary = Float.valueOf(response) * Float.valueOf(rs.getString(1)); 
                        stmt.executeUpdate("UPDATE salary SET \"2\" = '"+salary+"' WHERE id='"+userID+"'");
                    }
                }
                
                }
        }catch(ClassNotFoundException | SQLException e){ //JOptionPane.showMessageDialog(null, "Cannot connect Database !!!");
            e.printStackTrace();
        }
          catch(Exception e){
          JOptionPane.showMessageDialog(null, "Cannot be blank and must be number !!!");
          }
            onLoad();
    }//GEN-LAST:event_FebruaryActionPerformed

    private void JanuaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JanuaryActionPerformed
        // TODO add your handling code here:
       
        JFrame Paneframe = new JFrame("InputDialog Example #1");
        String response = JOptionPane.showInputDialog(Paneframe,"Insert your working hours in January here" );
          try{
             Class.forName("org.hsqldb.jdbc.JDBCDriver");
            try (Connection con = DriverManager.getConnection(
               "jdbc:hsqldb:file:HSQL/managing", "root", "")) {
                if(!renum.matches(response)&&Float.valueOf(response)%0.25!=0){
                    JOptionPane.showMessageDialog(null, "Must be number and multiples of 0.25 !");
                }
                else{
                    
                    String query="UPDATE monthly SET \"1\" = '"+ Float.valueOf(response) +"' WHERE id='"+userID+"'";
                    Statement stmt = (Statement) con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                    stmt.executeUpdate(query);
                    String hwage = "SELECT hswage FROM emp WHERE id = '"+ userID +"'";
                    ResultSet rs = stmt.executeQuery(hwage);
                    rs.first();
                    if(rs.getString(1).matches("0.0")){
                          float salary = Float.valueOf(response) * Float.valueOf(rs.getString(1)); 
                        stmt.executeUpdate("UPDATE salary SET \"1\" = '"+salary+"' WHERE id='"+userID+"'");
                    }
                }
                
                }
        }catch(ClassNotFoundException | SQLException e){ JOptionPane.showMessageDialog(null, "Cannot connect Database !!!");}
          catch(Exception e){
              e.printStackTrace();
          //JOptionPane.showMessageDialog(null, "Cannot be blank and must be number !!!");
          }
            onLoad();
        
    }//GEN-LAST:event_JanuaryActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null,">> Back to User Page <<", "Are you sure !!",YES_NO_OPTION,JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.YES_OPTION){
               this.setVisible(false);
               new empUI(empname).setVisible(true);
        }
    }//GEN-LAST:event_BackActionPerformed

    private void MarchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarchActionPerformed
        // TODO add your handling code here:
        
      JFrame Paneframe = new JFrame("InputDialog Example #1");
        String response = JOptionPane.showInputDialog(Paneframe,"Insert your working hours in January here" );
          try{
             Class.forName("org.hsqldb.jdbc.JDBCDriver");
            try (Connection con = DriverManager.getConnection(
               "jdbc:hsqldb:file:HSQL/managing", "root", "")) {
                if(!renum.matches(response)&&Float.valueOf(response)%0.25!=0){
                    JOptionPane.showMessageDialog(null, "Must be number and multiples of 0.25 !");
                }
                else{
                    String query="UPDATE monthly SET \"3\" = '"+ Float.valueOf(response) +"' WHERE id='"+userID+"'";
                    Statement stmt = (Statement) con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                    stmt.executeUpdate(query);
                    String hwage = "SELECT hswage FROM emp WHERE id = '"+ userID +"'";
                    ResultSet rs = stmt.executeQuery(hwage);
                    rs.first();
                    if(rs.getString(1).matches("0.0")){
                          float salary = Float.valueOf(response) * Float.valueOf(rs.getString(1)); 
                        stmt.executeUpdate("UPDATE salary SET \"3\" = '"+salary+"' WHERE id='"+userID+"'");
                    }
                }
                
                }
        }catch(ClassNotFoundException | SQLException e){ JOptionPane.showMessageDialog(null, "Cannot connect Database !!!");}
          catch(Exception e){
          JOptionPane.showMessageDialog(null, "Cannot be blank and must be number !!!");
          }
            onLoad();
        
    }//GEN-LAST:event_MarchActionPerformed

    private void AprilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AprilActionPerformed
        // TODO add your handling code here:String renum="[0-9]{1,100}";
      JFrame Paneframe = new JFrame("InputDialog Example #1");
        String response = JOptionPane.showInputDialog(Paneframe,"Insert your working hours in January here" );
          try{
             Class.forName("org.hsqldb.jdbc.JDBCDriver");
            try (Connection con = DriverManager.getConnection(
               "jdbc:hsqldb:file:HSQL/managing", "root", "")) {
                if(!renum.matches(response)&&Float.valueOf(response)%0.25!=0){
                    JOptionPane.showMessageDialog(null, "Must be number and multiples of 0.25 !");
                }
                else{
                    String query="UPDATE monthly SET \"4\" = '"+ Float.valueOf(response) +"' WHERE id='"+userID+"'";
                    Statement stmt = (Statement) con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                    stmt.executeUpdate(query);
                    String hwage = "SELECT hswage FROM emp WHERE id = '"+ userID +"'";
                    ResultSet rs = stmt.executeQuery(hwage);
                    rs.first();
                    if(rs.getString(1).matches("0.0")){
                          float salary = Float.valueOf(response) * Float.valueOf(rs.getString(1)); 
                        stmt.executeUpdate("UPDATE salary SET \"4\" = '"+salary+"' WHERE id='"+userID+"'");
                    }
                }
                
                }
        }catch(ClassNotFoundException | SQLException e){ JOptionPane.showMessageDialog(null, "Cannot connect Database !!!");}
          catch(Exception e){
          JOptionPane.showMessageDialog(null, "Cannot be blank and must be number !!!");
          }
            onLoad();
        
        
    }//GEN-LAST:event_AprilActionPerformed

    private void MayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MayActionPerformed
        // TODO add your handling code here:
      JFrame Paneframe = new JFrame("InputDialog Example #1");
        String response = JOptionPane.showInputDialog(Paneframe,"Insert your working hours in January here" );
          try{
             Class.forName("org.hsqldb.jdbc.JDBCDriver");
            try (Connection con = DriverManager.getConnection(
               "jdbc:hsqldb:file:HSQL/managing", "root", "")) {
                if(!renum.matches(response)&&Float.valueOf(response)%0.25!=0){
                    JOptionPane.showMessageDialog(null, "Must be number and multiples of 0.25 !");
                }
                else{
                    String query="UPDATE monthly SET \"5\" = '"+ Float.valueOf(response) +"' WHERE id='"+userID+"'";
                    Statement stmt = (Statement) con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                    stmt.executeUpdate(query);
                    String hwage = "SELECT hswage FROM emp WHERE id = '"+ userID +"'";
                    ResultSet rs = stmt.executeQuery(hwage);
                    rs.first();
                    if(rs.getString(1).matches("0.0")){
                          float salary = Float.valueOf(response) * Float.valueOf(rs.getString(1)); 
                        stmt.executeUpdate("UPDATE salary SET \"5\" = '"+salary+"' WHERE id='"+userID+"'");
                    }
                }
                
                }
        }catch(ClassNotFoundException | SQLException e){ JOptionPane.showMessageDialog(null, "Cannot connect Database !!!");}
          catch(Exception e){
          JOptionPane.showMessageDialog(null, "Cannot be blank and must be number !!!");
          }
            onLoad();
        
        
    }//GEN-LAST:event_MayActionPerformed

    private void JuneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JuneActionPerformed
        // TODO add your handling code here:
      JFrame Paneframe = new JFrame("InputDialog Example #1");
        String response = JOptionPane.showInputDialog(Paneframe,"Insert your working hours in January here" );
          try{
             Class.forName("org.hsqldb.jdbc.JDBCDriver");
            try (Connection con = DriverManager.getConnection(
               "jdbc:hsqldb:file:HSQL/managing", "root", "")) {
                if(!renum.matches(response)&&Float.valueOf(response)%0.25!=0){
                    JOptionPane.showMessageDialog(null, "Must be number and multiples of 0.25 !");
                }
                else{
                    String query="UPDATE monthly SET \"6\" = '"+ Float.valueOf(response) +"' WHERE id='"+userID+"'";
                    Statement stmt = (Statement) con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                    stmt.executeUpdate(query);
                    String hwage = "SELECT hswage FROM emp WHERE id = '"+ userID +"'";
                    ResultSet rs = stmt.executeQuery(hwage);
                    rs.first();
                   if(rs.getString(1).matches("0.0")){
                          float salary = Float.valueOf(response) * Float.valueOf(rs.getString(1)); 
                        stmt.executeUpdate("UPDATE salary SET \"6\" = '"+salary+"' WHERE id='"+userID+"'");
                    }
                }
                
                }
        }catch(ClassNotFoundException | SQLException e){ JOptionPane.showMessageDialog(null, "Cannot connect Database !!!");}
          catch(Exception e){
          JOptionPane.showMessageDialog(null, "Cannot be blank and must be number !!!");
          }
            onLoad();
        
        
    }//GEN-LAST:event_JuneActionPerformed

    private void JulyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JulyActionPerformed
        // TODO add your handling code here:
     JFrame Paneframe = new JFrame("InputDialog Example #1");
        String response = JOptionPane.showInputDialog(Paneframe,"Insert your working hours in January here" );
          try{
             Class.forName("org.hsqldb.jdbc.JDBCDriver");
            try (Connection con = DriverManager.getConnection(
               "jdbc:hsqldb:file:HSQL/managing", "root", "")) {
                if(!renum.matches(response)&&Float.valueOf(response)%0.25!=0){
                    JOptionPane.showMessageDialog(null, "Must be number and multiples of 0.25 !");
                }
                else{
                    String query="UPDATE monthly SET \"7\" = '"+ Float.valueOf(response) +"' WHERE id='"+userID+"'";
                    Statement stmt = (Statement) con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                    stmt.executeUpdate(query);
                    String hwage = "SELECT hswage FROM emp WHERE id = '"+ userID +"'";
                    ResultSet rs = stmt.executeQuery(hwage);
                    rs.first();
                    if(rs.getString(1).matches("0.0")){
                          float salary = Float.valueOf(response) * Float.valueOf(rs.getString(1)); 
                        stmt.executeUpdate("UPDATE salary SET \"7\" = '"+salary+"' WHERE id='"+userID+"'");
                    }
                }
                
                }
        }catch(ClassNotFoundException | SQLException e){ JOptionPane.showMessageDialog(null, "Cannot connect Database !!!");}
          catch(Exception e){
          JOptionPane.showMessageDialog(null, "Cannot be blank and must be number !!!");
          }
            onLoad();
        
        
    }//GEN-LAST:event_JulyActionPerformed

    private void AugustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AugustActionPerformed
        // TODO add your handling code here:
       JFrame Paneframe = new JFrame("InputDialog Example #1");
        String response = JOptionPane.showInputDialog(Paneframe,"Insert your working hours in January here" );
          try{
             Class.forName("org.hsqldb.jdbc.JDBCDriver");
            try (Connection con = DriverManager.getConnection(
               "jdbc:hsqldb:file:HSQL/managing", "root", "")) {
                if(!renum.matches(response)&&Float.valueOf(response)%0.25!=0){
                    JOptionPane.showMessageDialog(null, "Must be number and multiples of 0.25 !");
                }
                else{
                    String query="UPDATE monthly SET \"8\" = '"+ Float.valueOf(response) +"' WHERE id='"+userID+"'";
                    Statement stmt = (Statement) con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                    stmt.executeUpdate(query);
                    String hwage = "SELECT hswage FROM emp WHERE id = '"+ userID +"'";
                    ResultSet rs = stmt.executeQuery(hwage);
                    rs.first();
                    if(rs.getString(1).matches("0.0")){
                          float salary = Float.valueOf(response) * Float.valueOf(rs.getString(1)); 
                        stmt.executeUpdate("UPDATE salary SET \"8\" = '"+salary+"' WHERE id='"+userID+"'");
                    }
                }
                
                }
        }catch(ClassNotFoundException | SQLException e){ JOptionPane.showMessageDialog(null, "Cannot connect Database !!!");}
          catch(Exception e){
          JOptionPane.showMessageDialog(null, "Cannot be blank and must be number !!!");
          }
            onLoad();
        
        
    }//GEN-LAST:event_AugustActionPerformed

    private void SeptemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeptemberActionPerformed
        // TODO add your handling code here:
     JFrame Paneframe = new JFrame("InputDialog Example #1");
        String response = JOptionPane.showInputDialog(Paneframe,"Insert your working hours in January here" );
          try{
             Class.forName("org.hsqldb.jdbc.JDBCDriver");
            try (Connection con = DriverManager.getConnection(
               "jdbc:hsqldb:file:HSQL/managing", "root", "")) {
                if(!renum.matches(response)&&Float.valueOf(response)%0.25!=0){
                    JOptionPane.showMessageDialog(null, "Must be number and multiples of 0.25 !");
                }
                else{
                    String query="UPDATE monthly SET \"9\" = '"+ Float.valueOf(response) +"' WHERE id='"+userID+"'";
                    Statement stmt = (Statement) con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                    stmt.executeUpdate(query);
                    String hwage = "SELECT hswage FROM emp WHERE id = '"+ userID +"'";
                    ResultSet rs = stmt.executeQuery(hwage);
                    rs.first();
                   if(rs.getString(1).matches("0.0")){
                          float salary = Float.valueOf(response) * Float.valueOf(rs.getString(1)); 
                        stmt.executeUpdate("UPDATE salary SET \"9\" = '"+salary+"' WHERE id='"+userID+"'");
                    }
                }
                
                }
        }catch(ClassNotFoundException | SQLException e){ JOptionPane.showMessageDialog(null, "Cannot connect Database !!!");}
          catch(Exception e){
          JOptionPane.showMessageDialog(null, "Cannot be blank and must be number !!!");
          }
            onLoad();
        
    }//GEN-LAST:event_SeptemberActionPerformed

    private void OctoberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OctoberActionPerformed
        // TODO add your handling code here:
        JFrame Paneframe = new JFrame("InputDialog Example #1");
        String response = JOptionPane.showInputDialog(Paneframe,"Insert your working hours in January here" );
          try{
             Class.forName("org.hsqldb.jdbc.JDBCDriver");
            try (Connection con = DriverManager.getConnection(
               "jdbc:hsqldb:file:HSQL/managing", "root", "")) {
                if(!renum.matches(response)&&Float.valueOf(response)%0.25!=0){
                    JOptionPane.showMessageDialog(null, "Must be number and multiples of 0.25 !");
                }
                else{
                    String query="UPDATE monthly SET \"10\" = '"+ Float.valueOf(response) +"' WHERE id='"+userID+"'";
                    Statement stmt = (Statement) con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                    stmt.executeUpdate(query);
                    String hwage = "SELECT hswage FROM emp WHERE id = '"+ userID +"'";
                    ResultSet rs = stmt.executeQuery(hwage);
                    rs.first();
                     if(rs.getString(1).matches("0.0")){
                          float salary = Float.valueOf(response) * Float.valueOf(rs.getString(1)); 
                        stmt.executeUpdate("UPDATE salary SET \"10\" = '"+salary+"' WHERE id='"+userID+"'");
                    }
                }
                
                }
        }catch(ClassNotFoundException | SQLException e){ JOptionPane.showMessageDialog(null, "Cannot connect Database !!!");}
          catch(Exception e){
          JOptionPane.showMessageDialog(null, "Cannot be blank and must be number !!!");
          }
            onLoad();
        
        
    }//GEN-LAST:event_OctoberActionPerformed

    private void NovemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovemberActionPerformed
        // TODO add your handling code here:
     JFrame Paneframe = new JFrame("InputDialog Example #1");
        String response = JOptionPane.showInputDialog(Paneframe,"Insert your working hours in January here" );
          try{
             Class.forName("org.hsqldb.jdbc.JDBCDriver");
            try (Connection con = DriverManager.getConnection(
               "jdbc:hsqldb:file:HSQL/managing", "root", "")) {
                if(!renum.matches(response)&&Float.valueOf(response)%0.25!=0){
                    JOptionPane.showMessageDialog(null, "Must be number and multiples of 0.25 !");
                }
                else{
                    String query="UPDATE monthly SET \"11\" = '"+ Float.valueOf(response) +"' WHERE id='"+userID+"'";
                    Statement stmt = (Statement) con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                    stmt.executeUpdate(query);
                    String hwage = "SELECT hswage FROM emp WHERE id = '"+ userID +"'";
                    ResultSet rs = stmt.executeQuery(hwage);
                    rs.first();
                     if(rs.getString(1).matches("0.0")){
                          float salary = Float.valueOf(response) * Float.valueOf(rs.getString(1)); 
                        stmt.executeUpdate("UPDATE salary SET \"11\" = '"+salary+"' WHERE id='"+userID+"'");
                    }
                }
                
                }
        }catch(ClassNotFoundException | SQLException e){ JOptionPane.showMessageDialog(null, "Cannot connect Database !!!");}
          catch(Exception e){
          JOptionPane.showMessageDialog(null, "Cannot be blank and must be number !!!");
          }
            onLoad();
        
        
    }//GEN-LAST:event_NovemberActionPerformed

    private void DecemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecemberActionPerformed
        // TODO add your handling code here:
       JFrame Paneframe = new JFrame("InputDialog Example #1");
        String response = JOptionPane.showInputDialog(Paneframe,"Insert your working hours in January here" );
          try{
             Class.forName("org.hsqldb.jdbc.JDBCDriver");
            try (Connection con = DriverManager.getConnection(
               "jdbc:hsqldb:file:HSQL/managing", "root", "")) {
                if(!renum.matches(response)&&Float.valueOf(response)%0.25!=0){
                    JOptionPane.showMessageDialog(null, "Must be number and multiples of 0.25 !");
                }
                else{
                    String query="UPDATE monthly SET \"12\" = '"+ Float.valueOf(response) +"' WHERE id='"+userID+"'";
                    Statement stmt = (Statement) con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                    stmt.executeUpdate(query);
                    String hwage = "SELECT hswage FROM emp WHERE id = '"+ userID +"'";
                    ResultSet rs = stmt.executeQuery(hwage);
                    rs.first();
                     if(rs.getString(1).matches("0.0")){
                          float salary = Float.valueOf(response) * Float.valueOf(rs.getString(1)); 
                        stmt.executeUpdate("UPDATE salary SET \"12\" = '"+salary+"' WHERE id='"+userID+"'");
                    }
                }
                
                }
        }catch(ClassNotFoundException | SQLException e){ JOptionPane.showMessageDialog(null, "Cannot connect Database !!!");}
          catch(Exception e){
          JOptionPane.showMessageDialog(null, "Cannot be blank and must be number !!!");
          }
            onLoad();
        
        
    }//GEN-LAST:event_DecemberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimeSheets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimeSheets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimeSheets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimeSheets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimeSheets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton April;
    private javax.swing.JButton August;
    private javax.swing.JButton Back;
    private javax.swing.JButton December;
    private javax.swing.JButton February;
    private javax.swing.JButton January;
    private javax.swing.JButton July;
    private javax.swing.JButton June;
    private javax.swing.JButton March;
    private javax.swing.JButton May;
    private javax.swing.JButton November;
    private javax.swing.JButton October;
    private javax.swing.JButton September;
    private javax.swing.JLabel h1;
    private javax.swing.JLabel h10;
    private javax.swing.JLabel h11;
    private javax.swing.JLabel h12;
    private javax.swing.JLabel h2;
    private javax.swing.JLabel h3;
    private javax.swing.JLabel h4;
    private javax.swing.JLabel h5;
    private javax.swing.JLabel h6;
    private javax.swing.JLabel h7;
    private javax.swing.JLabel h8;
    private javax.swing.JLabel h9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables
}
