/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public final class UserManagement extends javax.swing.JFrame {
    Connection conn;
    Statement st;
    /**
     * Creates new form UserManagement
     */
    public UserManagement() {
        initComponents();
        Tableshow();
        Usershow();
       checkbutton();
    }
    
    public void Tableshow(){
        DefaultTableModel show = (DefaultTableModel)temptable.getModel();
            try{
                Class.forName("org.hsqldb.jdbc.JDBCDriver");
                //here manager is database name, root is username and password
                try (Connection con = DriverManager.getConnection(
                    "jdbc:hsqldb:file:HSQL/managing", "root", "")) {
                //here manager is database name, root is username and password
                Statement stmt=(Statement) con.createStatement();
                ResultSet rs=stmt.executeQuery("select * from temp order by id");
                //show it on screen
                while(rs.next()){
                   show.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)});
                }
                temptable.setModel(show);
              
            }
        }catch(ClassNotFoundException | SQLException e){ JOptionPane.showMessageDialog(null, "Cannot connect Database !!!");}
        
    }
    
    public void Usershow(){
        DefaultTableModel show = (DefaultTableModel)RegisMem.getModel();
            try{
                 Class.forName("org.hsqldb.jdbc.JDBCDriver");
                //here manager is database name, root is username and password
                try (Connection con = DriverManager.getConnection(
                     "jdbc:hsqldb:file:HSQL/managing", "root", "")) {
                //here manager is database name, root is username and password
                Statement stmt=(Statement) con.createStatement();
                ResultSet rs=stmt.executeQuery("select * from emp where id <>'admin' order by id");
                //show it on screen
                while(rs.next()){
                     show.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)});
                }
                RegisMem.setModel(show);
              
            }
        }catch(ClassNotFoundException | SQLException e){ JOptionPane.showMessageDialog(null, "Cannot connect Database !!!");}
        
    }
    public void checkbutton(){
        DefaultTableModel tmodel = (DefaultTableModel) temptable.getModel();
        if(tmodel.getRowCount()==0){
            abort.setEnabled(false);
            confirm.setEnabled(false);
        }
        else{
            abort.setEnabled(true);
            confirm.setEnabled(true);
        }
    }
    
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        exit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        temptable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        RegisMem = new javax.swing.JTable();
        confirm = new javax.swing.JButton();
        abort = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Management");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(77, 5, 232));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/icon/time-manager.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employee Management");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(41, 241, 195));
        jPanel3.setForeground(new java.awt.Color(77, 5, 232));
        jPanel3.setToolTipText("User Management");

        exit.setBackground(new java.awt.Color(255, 153, 51));
        exit.setFont(new java.awt.Font("Script MT Bold", 1, 12)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("Back");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(255, 0, 204));
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Employee work hours");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(77, 5, 232));
        jLabel3.setText("Registration Pending User");

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(77, 5, 232));
        jLabel4.setText("Current User");

        temptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Password", "Age", "Birth Place", "Email", "Salary"
            }
        )
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    jScrollPane3.setViewportView(temptable);

    RegisMem.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "ID", "Name", "Password", "Age ", "Birth Place", "Email", "Salary"
        }
    )
    {public boolean isCellEditable(int row, int column){return false;}}
    );
    jScrollPane4.setViewportView(RegisMem);

    confirm.setBackground(new java.awt.Color(0, 255, 0));
    confirm.setForeground(new java.awt.Color(255, 255, 255));
    confirm.setText("Confirm");
    confirm.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            confirmActionPerformed(evt);
        }
    });

    abort.setBackground(new java.awt.Color(255, 0, 0));
    abort.setForeground(new java.awt.Color(255, 255, 255));
    abort.setText("Abort");
    abort.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            abortActionPerformed(evt);
        }
    });

    jLabel17.setForeground(new java.awt.Color(255, 0, 0));
    jLabel17.setText("2020JIIT All rights reserved 18069 PHAM ANH CONG ");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane4)
                .addComponent(jScrollPane3)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(315, 315, 315)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(abort, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(24, 24, 24))
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(125, 125, 125)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(65, 65, 65)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jLabel17))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(jLabel3)
            .addGap(20, 20, 20)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(abort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(confirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(jLabel17)
            .addContainerGap(11, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abortActionPerformed
        // TODO add your handling code here:
        if(temptable.getSelectedRow()==-1){
            { JOptionPane.showMessageDialog(null, "No row selected !!!");}
        }else{
            int result = JOptionPane.showConfirmDialog(null,">> Abort this user ??? <<", "Abort !!!",YES_NO_OPTION,JOptionPane.PLAIN_MESSAGE);
            if (result == JOptionPane.YES_OPTION){
                try{
                   Class.forName("org.hsqldb.jdbc.JDBCDriver");

                    try (Connection con = DriverManager.getConnection(
                         "jdbc:hsqldb:file:HSQL/managing", "root", "")) {

                    Statement stmt=(Statement) con.createStatement();
                    //ResultSet rs=stmt.executeQuery("select * from emp");

                    int row = temptable.getSelectedRow();
                    String id = temptable.getModel().getValueAt(row, 0).toString();

                    stmt.executeUpdate("DELETE FROM temp WHERE id='"+id+"'");

                    DefaultTableModel model2 = (DefaultTableModel) temptable.getModel();
                    model2.setRowCount(0);
                    Tableshow();

                }
            }catch(ClassNotFoundException | SQLException e){ JOptionPane.showMessageDialog(null, "Cannot connect Database !!!");}
        }
        }
    }//GEN-LAST:event_abortActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
        if(temptable.getSelectedRow()==-1){
            { JOptionPane.showMessageDialog(null, "No row selected !!!");}
        }else{
            int result = JOptionPane.showConfirmDialog(null,">> Confirm this user ??? <<", "Con firm !!!",YES_NO_OPTION,JOptionPane.PLAIN_MESSAGE);
            if (result == JOptionPane.YES_OPTION){
                try{
                   Class.forName("org.hsqldb.jdbc.JDBCDriver");
                    //here manager is database name, root is username and password
                    try (Connection con = DriverManager.getConnection(
                         "jdbc:hsqldb:file:HSQL/managing", "root", "")) {

                    Statement stmt=(Statement) con.createStatement();
                    //ResultSet rs=stmt.executeQuery("select * from emp");

                    int row = temptable.getSelectedRow();
                    String id = temptable.getModel().getValueAt(row, 0).toString();
                    String name = temptable.getModel().getValueAt(row, 1).toString();
                    String password = temptable.getModel().getValueAt(row, 2).toString();
                    String age = temptable.getModel().getValueAt(row, 3).toString();
                    String bplace = temptable.getModel().getValueAt(row, 4).toString();
                    String email = temptable.getModel().getValueAt(row, 5).toString();
                    String hswage = temptable.getModel().getValueAt(row,6).toString();
                    stmt.executeUpdate("INSERT INTO emp VALUES('"+ id +"','"+ name+"','"+ password+"','"+ age+"','"+ bplace+"','"+ email+"','"+hswage+"')");
                    stmt.executeUpdate("INSERT INTO monthly VALUES('"+ id +"',0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)");
                    stmt.executeUpdate("INSERT INTO salary VALUES('"+ id +"',0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)");
                    stmt.executeUpdate("DELETE FROM temp WHERE id='"+ id +"'");
                    DefaultTableModel model = (DefaultTableModel) temptable.getModel();
                    DefaultTableModel model2 = (DefaultTableModel) RegisMem.getModel();
                    model.setRowCount(0);
                    model2.setRowCount(0);
                    Tableshow();
                    Usershow();
                }
            }catch(ClassNotFoundException | SQLException e){ JOptionPane.showMessageDialog(null, "Cannot connect Database !!!");}
        }
        }
    }//GEN-LAST:event_confirmActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null," Go to Work hours Manage Page ? ", "Are you sure !!",YES_NO_OPTION,JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.YES_OPTION){
            this.setVisible(false);
            new SalaryShows().setVisible(true);
        }

    }//GEN-LAST:event_deleteActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:

        int result = JOptionPane.showConfirmDialog(null,">> Back to Admin Page <<", "Are you sure !!",YES_NO_OPTION,JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.YES_OPTION){
            this.setVisible(false);
            new admin().setVisible(true);
        }
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable RegisMem;
    private javax.swing.JButton abort;
    private javax.swing.JButton confirm;
    private javax.swing.JButton delete;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable temptable;
    // End of variables declaration//GEN-END:variables
}
